import type { TranspiledCell } from "./transpile.js";

export function generateDefineJs(cells: TranspiledCell[]): string {
    const lines = [
        `// Auto-generated by notebook-to-lib`,
        `export default function define(runtime, observer) {`,
        `  const main = runtime.module();`
    ];

    cells.forEach(cell => {
        // Convert inputs array to string literal: ["a", "b"]
        const inputs = JSON.stringify(cell.inputs);

        // For cells with outputs, define once and let the Observable Runtime handle the multiple outputs
        // The body should return an object with all outputs
        if (cell.outputs.length === 0) {
            // Side-effect cell (like markdown or console.log)
            const cellName = cell.name ? `"${cell.name}"` : "null";
            lines.push(`  main.variable(observer(${cellName})).define(${inputs}, ${cell.body});`);
        } else if (cell.outputs.length === 1) {
            // Single output cell
            const output = cell.outputs[0];
            lines.push(`  main.variable(observer("${output}")).define("${output}", ${inputs}, ${cell.body});`);
        } else {
            // Multiple outputs - define the first one as the primary variable
            // The body returns an object, so the runtime will handle destructuring
            const primaryOutput = cell.outputs[0];
            lines.push(`  main.variable(observer("${primaryOutput}")).define("${primaryOutput}", ${inputs}, ${cell.body});`);
        }
    });

    lines.push(`  return main;`);
    lines.push(`}`);

    return lines.join("\n");
}

export function generateIndexJs(): string {
    return `export { default } from "./define.js";`;
}

export function generatePackageJson(name: string, dependencies: Set<string>): string {
    const depsObj: Record<string, string> = {
        "@observablehq/runtime": "^5.0.0"
    };

    // Add detected dependencies
    // We default to "latest" because we extracted names but not versions
    dependencies.forEach(dep => {
        depsObj[dep] = "latest";
    });

    return JSON.stringify({
        name,
        version: "0.1.0",
        description: "Converted Observable Notebook",
        type: "module",
        main: "src/index.js",
        files: ["src"],
        dependencies: depsObj
    }, null, 2);
}

export function generateReadme(name: string): string {
    return `# ${name}

This library was generated from an Observable Notebook.

## Usage

\`\`\`javascript
import { Runtime, Inspector } from "@observablehq/runtime";
import define from "${name}";

const runtime = new Runtime();
const main = runtime.module(define, Inspector.into(document.body));
\`\`\`
`;
}
